// This file is generated by CMake. Do not edit by hand.
#pragma once

#include <AICombat/BigBrawlerStateMachine.hpp>
#include <AICombat/Bolt.hpp>
#include <AICombat/BrawlerStateMachine.hpp>
#include <AICombat/HammerDamage.hpp>
#include <AICombat/MageDamage.hpp>
#include <ECSExample/ECSExampleComponents.hpp>
#include <ECSExample/ECSExampleSystems.hpp>
#include <RollABall/BoostPad.hpp>
#include <RollABall/LaserTagTurret.hpp>
#include <RollABall/PauseMenuController.hpp>
#include <RollABall/PickupSpinner.hpp>
#include <RollABall/PlayerController.hpp>
#include <RollABall/StartMenu.hpp>
#include <SuperPupUtilities/Bullet.hpp>
#include <SuperPupUtilities/FPSCounter.hpp>
#include <SuperPupUtilities/Inventory.hpp>
#include <SuperPupUtilities/SimpleObjectPool.hpp>
#include <TankGame/Bounce.hpp>
#include <TankGame/Bullet.hpp>
#include <TankGame/FollowMouse.hpp>
#include <TankGame/Tank.hpp>


inline void RegisterGeneratedGameContent(Canis::App &_app)
{
    AICombat::RegisterBigBrawlerStateMachineScript(_app);
    AICombat::RegisterBoltScript(_app);
    AICombat::RegisterBrawlerStateMachineScript(_app);
    AICombat::RegisterHammerDamageScript(_app);
    AICombat::RegisterMageDamageScript(_app);
    ECSExample::RegisterCollectibleComponent(_app);
    ECSExample::RegisterCollectibleSystem(_app);
    ECSExample::RegisterHoverComponent(_app);
    ECSExample::RegisterHoverSystem(_app);
    ECSExample::RegisterSampleHUDComponent(_app);
    ECSExample::RegisterSampleHUDSystem(_app);
    ECSExample::RegisterSamplePlayerComponent(_app);
    ECSExample::RegisterSamplePlayerSystem(_app);
    ECSExample::RegisterSpinComponent(_app);
    ECSExample::RegisterSpinSystem(_app);
    RollABall::RegisterBoostPadScript(_app);
    RollABall::RegisterLaserTagTurretScript(_app);
    RollABall::RegisterPauseMenuControllerScript(_app);
    RollABall::RegisterPickupSpinnerScript(_app);
    RollABall::RegisterPlayerControllerScript(_app);
    RollABall::RegisterStartMenuScript(_app);
    SuperPupUtilities::RegisterBulletScript(_app);
    SuperPupUtilities::RegisterFPSCounterScript(_app);
    SuperPupUtilities::RegisterInventoryScript(_app);
    SuperPupUtilities::RegisterSimpleObjectPoolScript(_app);
    TankGame::RegisterBounceScript(_app);
    TankGame::RegisterBulletScript(_app);
    TankGame::RegisterFollowMouseScript(_app);
    TankGame::RegisterTankScript(_app);
}

inline void UnRegisterGeneratedGameContent(Canis::App &_app)
{
    AICombat::UnRegisterBigBrawlerStateMachineScript(_app);
    AICombat::UnRegisterBoltScript(_app);
    AICombat::UnRegisterBrawlerStateMachineScript(_app);
    AICombat::UnRegisterHammerDamageScript(_app);
    AICombat::UnRegisterMageDamageScript(_app);
    ECSExample::UnRegisterCollectibleComponent(_app);
    ECSExample::UnRegisterCollectibleSystem(_app);
    ECSExample::UnRegisterHoverComponent(_app);
    ECSExample::UnRegisterHoverSystem(_app);
    ECSExample::UnRegisterSampleHUDComponent(_app);
    ECSExample::UnRegisterSampleHUDSystem(_app);
    ECSExample::UnRegisterSamplePlayerComponent(_app);
    ECSExample::UnRegisterSamplePlayerSystem(_app);
    ECSExample::UnRegisterSpinComponent(_app);
    ECSExample::UnRegisterSpinSystem(_app);
    RollABall::UnRegisterBoostPadScript(_app);
    RollABall::UnRegisterLaserTagTurretScript(_app);
    RollABall::UnRegisterPauseMenuControllerScript(_app);
    RollABall::UnRegisterPickupSpinnerScript(_app);
    RollABall::UnRegisterPlayerControllerScript(_app);
    RollABall::UnRegisterStartMenuScript(_app);
    SuperPupUtilities::UnRegisterBulletScript(_app);
    SuperPupUtilities::UnRegisterFPSCounterScript(_app);
    SuperPupUtilities::UnRegisterInventoryScript(_app);
    SuperPupUtilities::UnRegisterSimpleObjectPoolScript(_app);
    TankGame::UnRegisterBounceScript(_app);
    TankGame::UnRegisterBulletScript(_app);
    TankGame::UnRegisterFollowMouseScript(_app);
    TankGame::UnRegisterTankScript(_app);
}

inline void RegisterGeneratedScripts(Canis::App &_app)
{
    RegisterGeneratedGameContent(_app);
}

inline void UnRegisterGeneratedScripts(Canis::App &_app)
{
    UnRegisterGeneratedGameContent(_app);
}
